title: Modular Flows Differential Molecular Generation
description: In Neural Information Processing Systems (NeurIPS), 2022
author: Yogesh Verma, Samuel Kaski, Markus Heinonen, Vikas Garg
theme: jekyll-theme-cayman
